FILES=src/get_files.rs src/bin.rs src/lib.rs src/link.rs src/setup.rs
BINARY=target/release/rdfm

$(BINARY) : $(FILES)
	cargo build --release

install : $(BINARY)
	cp $(BINARY) /usr/bin/
	chown root:root /usr/bin/rdfm
	chmod 711 /usr/bin/rdfm
